Port to LLVM 11.0.0 + basic refactoring via Resharper
dwat3r/slicer pull request #5
Opened 2021-02-17 13:05 UTC by leskovde

Code cleanup, setup summary and changes to the newest LLVM / libTooling framework.

2021-02-27 04:58 UTC, dwat3r requested changes
Hey, thanks for updating my project!

I have a couple of suggestions:
Please use 2 spaces when formatting.
, 4 spaces makes the code too wide.

Please don't delete png files, as they are important showcase what this tool can do.

Could you tell me why do you need this PR to be merged? I'm asking out of curiosity. Updating is nice really.

2021-02-27 04:58 UTC, dwat3r commented on test/dot2png.bat
> +for %%v in (*.dot) do "C:\Program Files\Graphviz 2.44.1\bin\dot.exe" -Tpng "%%v" -o "%%~nv.png"
Please make this a relative path, like 'dot.exe', for portability.

2021-03-08 10:09 UTC, leskovde commented
Hello,
I've reverted all the PNG files I've modified or removed on accident as well as the formatting of the code. 

I'm working on a bachelor thesis. During my research, I was looking for Clang-based slicers and yours is one of the few I've found. I tried to run the code on the latest release of LLVM, however, due to frequent changes to Clang and LibTooling, it just wouldn't compile. 
I've decided that it would be useful for others to update the project to the latest release, rather than download an outdated version of LLVM (which, as I've found out, is not always possible on some systems).

Thanks for making this project available. I'll make sure to reference it in my work :)

Cheers!

2021-03-08 10:56 UTC, dwat3r commented
Thank you, this work was my masters thesis, so I'm happy that you've found it useful for yours! :)
Thank you again putting effort into it.
The thing is that it has limited slicing capabilities, so a lot of improvements could be made, but I was lazy to work on it after finishing MSc.

One of the challenges are to make it work with classes, and to slice the whole compilation unit, across functions, excluding standard libraries.

The PR now looks now great, so I'll merge it.

2021-03-08 10:56 UTC, dwat3r approved these changes

2021-03-08 10:56 UTC, merged